#!/bin/bash
#SBATCH --job-name=dropout02
#SBATCH --mail-type=ALL
#SBATCH --mail-user=tommaso.azzalin@studio.unibo.it
#SBATCH --time=10:00:00
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --output=dropout02
#SBATCH --gres=gpu:1

cd ../

. venv/bin/activate # per attivare il virtual environment python

pip3 install --no-cache-dir -r requirements.txt

export DROPOUT_LAYER=True
export DROPOUT_LAYER_RATE=0.2

python3 src/invalsi.py