MAPPING_DOMANDE_AMBITI_PROCESSI = {
    'D1' : ('Numeri', 'Conoscere e utilizzare algoritmi e procedure'),
    'D2' : ('Dati e previsioni', 'Conoscere e padroneggiare i contenuti specifici della matematica'),
    'D3_a' : ('Dati e previsioni', 'Utilizzare strumenti, modelli e rappresentazioni nel trattamento quantitativo dell\'informazione in ambito scientifico, tecnologico, economico e sociale'),
    'D3_b': ('Numeri', 'Conoscere e utilizzare algoritmi e procedure'),
    'D4_a' : ('Spazio figure', 'Riconoscere le forme nello spazio e utilizzarle per la risoluzione di problemi geometrici o di modellizzazione'),
    'D4_b' : ('Spazio figure', 'Riconoscere le forme nello spazio e utilizzarle per la risoluzione di problemi geometrici o di modellizzazione'),
    'D4_c' : ('Spazio figure', 'Riconoscere le forme nello spazio e utilizzarle per la risoluzione di problemi geometrici o di modellizzazione'),
    'D4_d' : ('Spazio figure', 'Riconoscere le forme nello spazio e utilizzarle per la risoluzione di problemi geometrici o di modellizzazione'),
    'D5_a' : ('Relazioni e funzioni', 'Conoscere e utilizzare algoritmi e procedure'),
    'D5_b' : ('Relazioni e funzioni', 'Utilizzare strumenti, modelli e rappresentazioni nel trattamento quantitativo dell\'informazione in ambito scientifico, tecnologico, economico e sociale'),
    'D6' : ('Numeri', 'Acquisire progressivamente forme tipiche del pensiero matematico'),
    'D7_a' : ('Numeri', 'Conoscere e padroneggiare i contenuti specifici della matematica'),
    'D7_b' : ('Numeri', 'Conoscere e padroneggiare i contenuti specifici della matematica'),
    'D8' : ('Spazio figure', 'Riconoscere le forme nello spazio e utilizzarle per la risoluzione di problemi geometrici o di modellizzazione'),
    'D9' : ('Relazioni e funzioni', 'Utilizzare strumenti, modelli e rappresentazioni nel trattamento quantitativo dell\'informazione in ambito scientifico, tecnologico, economico e sociale'),
    'D10_a'  : ('Relazioni e funzioni', 'Rappresentare relazioni e dati e, in situazioni significative, utilizzare le rappresentazioni per ricavare informazioni, formulare giudizi e prendere decisioni'),
    'D10_b1' : ('Relazioni e funzioni', 'Rappresentare relazioni e dati e, in situazioni significative, utilizzare le rappresentazioni per ricavare informazioni, formulare giudizi e prendere decisioni'),
    'D10_b2' : ('Relazioni e funzioni', 'Rappresentare relazioni e dati e, in situazioni significative, utilizzare le rappresentazioni per ricavare informazioni, formulare giudizi e prendere decisioni'),
    'D10_b3' : ('Relazioni e funzioni', 'Rappresentare relazioni e dati e, in situazioni significative, utilizzare le rappresentazioni per ricavare informazioni, formulare giudizi e prendere decisioni'),
    'D11_a' : ('Spazio figure', 'Riconoscere in contesti diversi il carattere misurabile di oggetti e fenomeni, utilizzare strumenti di misura, misurare grandezze, stimare misure di grandezze'),
    'D11_b' : ('Spazio figure', 'Conoscere e utilizzare algoritmi e procedure'),
    'D12_a' : ('Numeri', 'Risolvere problemi utilizzando strategie in ambiti diversi – numerico, geometrico, algebrico –'),
    'D12_b' : ('Numeri', 'Risolvere problemi utilizzando strategie in ambiti diversi – numerico, geometrico, algebrico –'),
    'D13_a' : ('Dati e previsioni', 'Utilizzare strumenti, modelli e rappresentazioni nel trattamento quantitativo dell\'informazione in ambito scientifico, tecnologico, economico e sociale'),
    'D13_b' : ('Dati e previsioni', 'Utilizzare strumenti, modelli e rappresentazioni nel trattamento quantitativo dell\'informazione in ambito scientifico, tecnologico, economico e sociale'),
    'D13_c' : ('Dati e previsioni', 'Utilizzare strumenti, modelli e rappresentazioni nel trattamento quantitativo dell\'informazione in ambito scientifico, tecnologico, economico e sociale'),
    'D14' : ('Relazioni e funzioni', 'Acquisire progressivamente forme tipiche del pensiero matematico'),
    'D15' : ('Dati e previsioni', 'Conoscere e utilizzare algoritmi e procedure'),
    'D16_a' : ('Dati e previsioni', 'Utilizzare strumenti, modelli e rappresentazioni nel trattamento quantitativo dell\'informazione in ambito scientifico, tecnologico, economico e sociale'),
    'D16_b' : ('Dati e previsioni', 'Utilizzare strumenti, modelli e rappresentazioni nel trattamento quantitativo dell\'informazione in ambito scientifico, tecnologico, economico e sociale'),
    'D16_c' : ('Dati e previsioni', 'Utilizzare strumenti, modelli e rappresentazioni nel trattamento quantitativo dell\'informazione in ambito scientifico, tecnologico, economico e sociale'),
    'D16_d' : ('Dati e previsioni', 'Utilizzare strumenti, modelli e rappresentazioni nel trattamento quantitativo dell\'informazione in ambito scientifico, tecnologico, economico e sociale'),
    'D17_a' : ('Numeri', 'Riconoscere in contesti diversi il carattere misurabile di oggetti e fenomeni, utilizzare strumenti di misura, misurare grandezze, stimare misure di grandezze'),
    'D17_b' : ('Numeri', 'Riconoscere in contesti diversi il carattere misurabile di oggetti e fenomeni, utilizzare strumenti di misura, misurare grandezze, stimare misure di grandezze'),
    'D18' : ('Spazio figure', 'Conoscere e utilizzare algoritmi e procedure'),
    'D19_a' : ('Spazio figure', 'Risolvere problemi utilizzando strategie in ambiti diversi – numerico, geometrico, algebrico –'),
    'D19_b' : ('Spazio figure', 'Risolvere problemi utilizzando strategie in ambiti diversi – numerico, geometrico, algebrico –'),
    'D20' : ('Dati e previsioni', 'Conoscere e utilizzare algoritmi e procedure'),
    'D21' : ('Numeri', 'Riconoscere in contesti diversi il carattere misurabile di oggetti e fenomeni, utilizzare strumenti di misura, misurare grandezze, stimare misure di grandezze'),
    'D22' : ('Spazio figure', 'Acquisire progressivamente forme tipiche del pensiero matematico'),
    'D23_a' : ('Relazioni e funzioni', 'Acquisire progressivamente forme tipiche del pensiero matematico'),
    'D23_b' : ('Relazioni e funzioni', 'Acquisire progressivamente forme tipiche del pensiero matematico'),
    'D23_c' : ('Relazioni e funzioni', 'Acquisire progressivamente forme tipiche del pensiero matematico'),
    'D23_d' : ('Relazioni e funzioni', 'Acquisire progressivamente forme tipiche del pensiero matematico'),
    'D24_a' : ('Relazioni e funzioni', 'Conoscere e padroneggiare i contenuti specifici della matematica'),
    'D24_b' : ('Relazioni e funzioni', 'Utilizzare strumenti, modelli e rappresentazioni nel trattamento quantitativo dell\'informazione in ambito scientifico, tecnologico, economico e sociale'),
    'D25' : ('Spazio figure', 'Conoscere e utilizzare algoritmi e procedure'),
    'D26_a': ('Numeri', 'Conoscere e padroneggiare i contenuti specifici della matematica'),
    'D26_b': ('Numeri', 'Conoscere e padroneggiare i contenuti specifici della matematica'),
    'D26_c': ('Numeri', 'Conoscere e padroneggiare i contenuti specifici della matematica'),
    'D26_d': ('Numeri', 'Conoscere e padroneggiare i contenuti specifici della matematica')
}